question_data = [{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "French is an official language in Canada.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "The color orange is named after the fruit.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "When you cry in space, your tears stick to your face.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                      "question": "The mitochondria is the powerhouse of the cell.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}]
